### ISSUE TITLE
TrustFLEX issue with AWS Custom PKI use case

### ISSUE THREAD

**Issue by bugabuga64** [Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker#16]
Issue Type: <b>Bug Report</b>
#### tpds-voila-template: 2.2.3

When computing step2 in the AWS custom PKI bugs. 

![image](https://github.com/user-attachments/assets/7489f51d-96c9-4822-b5b9-1b732eb97c97)

**Log from TPDS right window in the use case**

Connecting to Secure Element: factory_programmed
OK
Device details: {'revision': '00006003', 'serial_number': '01233CAA8D56864301', 'lock_status': [True, True]}
Generating CustomPKI certs...
MCHP Certs are available on device
User Org Name: dewfeerqf
-----BEGIN CERTIFICATE-----
MIIB0zCCAXmgAwIBAgIQebVtY8fn2f24BjGPcvn2pzAKBggqhkjOPQQDAjBAMRIw
EAYDVQQKDAlkZXdmZWVycWYxKjAoBgNVBAMMIUNyeXB0byBBdXRoZW50aWNhdGlv
biBSb290IENBIDAwMjAgFw0yNDExMTkyMDAzMDNaGA8yMDY0MTExOTIwMDMwM1ow
QDESMBAGA1UECgwJZGV3ZmVlcnFmMSowKAYDVQQDDCFDcnlwdG8gQXV0aGVudGlj
YXRpb24gUm9vdCBDQSAwMDIwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAROk0rI
5FKssmmpspm6q0wYmG0h/vlV/UJmUP1NyeEawPMhgUXKr+/xnJU5tXwRH65/l6P7
l/OVKe75LLOBWw6qo1MwUTAdBgNVHQ4EFgQUfGuBcdl/Yxkx/iNVlufaV0qYzfAw
HwYDVR0jBBgwFoAUfGuBcdl/Yxkx/iNVlufaV0qYzfAwDwYDVR0TAQH/BAUwAwEB
/zAKBggqhkjOPQQDAgNIADBFAiEA7jyIK+QSttMkL34Twg9hOBBnvPT0V9tzT2LR
8i6R0jsCIErwgWIjAulrSXHT0HqZVatDftwKRjnOoUijUcN5r78Q
-----END CERTIFICATE-----

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            79:b5:6d:63:c7:e7:d9:fd:b8:06:31:8f:72:f9:f6:a7
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: O=dewfeerqf, CN=Crypto Authentication Root CA 002
        Validity
            Not Before: Nov 19 20:03:03 2024 GMT
            Not After : Nov 19 20:03:03 2064 GMT
        Subject: O=dewfeerqf, CN=Crypto Authentication Root CA 002
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:4e:93:4a:c8:e4:52:ac:b2:69:a9:b2:99:ba:ab:
                    4c:18:98:6d:21:fe:f9:55:fd:42:66:50:fd:4d:c9:
                    e1:1a:c0:f3:21:81:45:ca:af:ef:f1:9c:95:39:b5:
                    7c:11:1f:ae:7f:97:a3:fb:97:f3:95:29:ee:f9:2c:
                    b3:81:5b:0e:aa
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                7C:6B:81:71:D9:7F:63:19:31:FE:23:55:96:E7:DA:57:4A:98:CD:F0
            X509v3 Authority Key Identifier: 
                keyid:7C:6B:81:71:D9:7F:63:19:31:FE:23:55:96:E7:DA:57:4A:98:CD:F0

            X509v3 Basic Constraints: critical
                CA:TRUE
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:21:00:ee:3c:88:2b:e4:12:b6:d3:24:2f:7e:13:c2:
         0f:61:38:10:67:bc:f4:f4:57:db:73:4f:62:d1:f2:2e:91:d2:
         3b:02:20:4a:f0:81:62:23:02:e9:6b:49:71:d3:d0:7a:99:55:
         ab:43:7e:dc:0a:46:39:ce:a1:48:a3:51:c3:79:af:bf:10

-----BEGIN CERTIFICATE-----
MIIB5jCCAYygAwIBAgIQT1SOxVZd1hvrSiBcVWxuFTAKBggqhkjOPQQDAjBAMRIw
EAYDVQQKDAlkZXdmZWVycWYxKjAoBgNVBAMMIUNyeXB0byBBdXRoZW50aWNhdGlv
biBSb290IENBIDAwMjAgFw0yNDExMTkyMDAwMDBaGA8yMDU1MTExOTIwMDAwMFow
QDESMBAGA1UECgwJZGV3ZmVlcnFmMSowKAYDVQQDDCFDcnlwdG8gQXV0aGVudGlj
YXRpb24gU2lnbmVyIEZGRkYwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAATCFQ0c
eJr5mT6dCTOnwQfkO2wOZ9PdEbIyChnvxILIcILx+5+Boby1VKxlC6ayuVPP9nar
NPRiBG+q3BVN5BnGo2YwZDAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB
/wIBADAdBgNVHQ4EFgQUZKU1cUhnB5MtAG+15v5chqMxRTYwHwYDVR0jBBgwFoAU
fGuBcdl/Yxkx/iNVlufaV0qYzfAwCgYIKoZIzj0EAwIDSAAwRQIhAKNDlKjDPZXC
8JSk3EWyJLWzvceGWyIazuu3fUshxo7GAiBoB3rx3O+EicVYQ87s076FLHXQeUWg
bNrumFfN+2bhig==
-----END CERTIFICATE-----

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            4f:54:8e:c5:56:5d:d6:1b:eb:4a:20:5c:55:6c:6e:15
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: O=dewfeerqf, CN=Crypto Authentication Root CA 002
        Validity
            Not Before: Nov 19 20:00:00 2024 GMT
            Not After : Nov 19 20:00:00 2055 GMT
        Subject: O=dewfeerqf, CN=Crypto Authentication Signer FFFF
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:c2:15:0d:1c:78:9a:f9:99:3e:9d:09:33:a7:c1:
                    07:e4:3b:6c:0e:67:d3:dd:11:b2:32:0a:19:ef:c4:
                    82:c8:70:82:f1:fb:9f:81:a1:bc:b5:54:ac:65:0b:
                    a6:b2:b9:53:cf:f6:76:ab:34:f4:62:04:6f:aa:dc:
                    15:4d:e4:19:c6
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE, pathlen:0
            X509v3 Subject Key Identifier: 
                64:A5:35:71:48:67:07:93:2D:00:6F:B5:E6:FE:5C:86:A3:31:45:36
            X509v3 Authority Key Identifier: 
                keyid:7C:6B:81:71:D9:7F:63:19:31:FE:23:55:96:E7:DA:57:4A:98:CD:F0

    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:21:00:a3:43:94:a8:c3:3d:95:c2:f0:94:a4:dc:45:
         b2:24:b5:b3:bd:c7:86:5b:22:1a:ce:eb:b7:7d:4b:21:c6:8e:
         c6:02:20:68:07:7a:f1:dc:ef:84:89:c5:58:43:ce:ec:d3:be:
         85:2c:75:d0:79:45:a0:6c:da:ee:98:57:cd:fb:66:e1:8a

-----BEGIN CERTIFICATE-----
MIIB1DCCAXmgAwIBAgIQZULTRb74Qg+POIOFxURbyDAKBggqhkjOPQQDAjBAMRIw
EAYDVQQKDAlkZXdmZWVycWYxKjAoBgNVBAMMIUNyeXB0byBBdXRoZW50aWNhdGlv
biBTaWduZXIgRkZGRjAgFw0yNDExMTkyMDAwMDBaGA8yMDUyMTExOTIwMDAwMFow
MzESMBAGA1UECgwJZGV3ZmVlcnFmMR0wGwYDVQQDDBRzbjAxMjMzQ0FBOEQ1Njg2
NDMwMTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLlcNqkUmos8SQvIdlnmNQ+v
UhNA57xmsTiXTa3QZVU9se1RBwUY7m2iEtv5ITpdHGU8OFlpzqZO8IdnJFLf0kKj
YDBeMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgOIMB0GA1UdDgQWBBSZ4bUN
Dgh6TSfQ9BgkO6K3JGtjTzAfBgNVHSMEGDAWgBRkpTVxSGcHky0Ab7Xm/lyGozFF
NjAKBggqhkjOPQQDAgNJADBGAiEAlvpqJ3TkCQ2HQNDBGT/WQEbRT3c25mEwLaj+
a0IQyLQCIQCnHYljFSAK0f+GE+D1pefB1z6D+FsRB3q7VoQxR0qOBw==
-----END CERTIFICATE-----

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            65:42:d3:45:be:f8:42:0f:8f:38:83:85:c5:44:5b:c8
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: O=dewfeerqf, CN=Crypto Authentication Signer FFFF
        Validity
            Not Before: Nov 19 20:00:00 2024 GMT
            Not After : Nov 19 20:00:00 2052 GMT
        Subject: O=dewfeerqf, CN=sn01233CAA8D56864301
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:b9:5c:36:a9:14:9a:8b:3c:49:0b:c8:76:59:e6:
                    35:0f:af:52:13:40:e7:bc:66:b1:38:97:4d:ad:d0:
                    65:55:3d:b1:ed:51:07:05:18:ee:6d:a2:12:db:f9:
                    21:3a:5d:1c:65:3c:38:59:69:ce:a6:4e:f0:87:67:
                    24:52:df:d2:42
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Key Usage: critical
                Digital Signature, Key Agreement
            X509v3 Subject Key Identifier: 
                99:E1:B5:0D:0E:08:7A:4D:27:D0:F4:18:24:3B:A2:B7:24:6B:63:4F
            X509v3 Authority Key Identifier: 
                keyid:64:A5:35:71:48:67:07:93:2D:00:6F:B5:E6:FE:5C:86:A3:31:45:36

    Signature Algorithm: ecdsa-with-SHA256
         30:46:02:21:00:96:fa:6a:27:74:e4:09:0d:87:40:d0:c1:19:
         3f:d6:40:46:d1:4f:77:36:e6:61:30:2d:a8:fe:6b:42:10:c8:
         b4:02:21:00:a7:1d:89:63:15:20:0a:d1:ff:86:13:e0:f5:a5:
         e7:c1:d7:3e:83:f8:5b:11:07:7a:bb:56:84:31:47:4a:8e:07

Executed Step-1 Successfully

Configure AWS CLI...
Setting aws access key...OK
Setting aws secret access key...OK
Setting aws region...OK
Created policy Default

Error while executing Step-2
Traceback (most recent call last):
  File "C:\Users\C16779\tpds\2.3.9\lib\site-packages\tpds\usecase_diagram\canvas.py", line 320, in render
    self.call_back(b=None)
  File "C:\Users\C16779\tpds\2.3.9\lib\site-packages\tpds_extension\cloud_connect\TrustFlex\assets\python\aws_connect.py", line 112, in register_certificates
    self.connect_to_cloud(b)
  File "C:\Users\C16779\tpds\2.3.9\lib\site-packages\tpds_extension\cloud_connect\TrustFlex\assets\python\aws_connect.py", line 46, in connect_to_cloud
    resp_data = self.__config_aws_cli(b)
  File "C:\Users\C16779\tpds\2.3.9\lib\site-packages\tpds_extension\cloud_connect\TrustFlex\assets\python\aws_connect.py", line 59, in __config_aws_cli
    self.connection.set_credentials(aws_credentials)
  File "C:\Users\C16779\tpds\2.3.9\lib\site-packages\tpds\cloud_connect\aws_connect.py", line 149, in set_credentials
    self.iot.describe_endpoint(endpointType="iot:Data").get("endpointAddress")
  File "C:\Users\C16779\tpds\2.3.9\lib\site-packages\botocore\client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\C16779\tpds\2.3.9\lib\site-packages\botocore\client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidRequestException: An error occurred (InvalidRequestException) when calling the DescribeEndpoint operation: iot:Data is not supported. Please use iot:Data-ATS instead.

**See above iot:Data needs to be iot:Data-ATS as AWS informed us.** 

**CMD log** 

The launcher has determined that the parent process has a console and will reuse it for its own console output.
Closing the console will result in termination of the running program.
Use '--console suppress' to suppress console output.
Use '--console new' to create a separate console window.
←[32mINFO←[0m:     ('127.0.0.1', 54809) - "WebSocket /websocket" [accepted]
[DEBUG 2024-11-19 12:15:48,833 40348 33328] Websocket - Connecting Address(host='127.0.0.1', port=54809):Address(host='127.0.0.1', port=54809) as 83d8713b71914961
←[32mINFO←[0m:     connection open
[DEBUG 2024-11-19 12:15:48,839 40348 33328] Websocket - Recieved {"msg_id": 3, "parameters": ["C:\\Users\\C16779\\tpds\\2.3.9\\lib\\site-packages\\tpds_extension\\cloud_connect\\TrustFlex\\assets\\AWS Connect.md"], "app_id": "fcbeb924595a9d88"} from 83d8713b71914961
[DEBUG 2024-11-19 12:15:48,841 40348 33328] Processing Message: msg_id=<ReservedMessageId.open_webview: 3> parameters=['C:\\Users\\C16779\\tpds\\2.3.9\\lib\\site-packages\\tpds_extension\\cloud_connect\\TrustFlex\\assets\\AWS Connect.md'] app_id='fcbeb924595a9d88'
[DEBUG 2024-11-19 12:15:48,841 40348 33328] open_webview: MessageContext(parent=<tpds.app.app.TPDSApplication(0x25c868969e0) at 0x0000025C88736680>, message=OperationMessage(msg_id=<ReservedMessageId.open_webview: 3>, parameters=['C:\\Users\\C16779\\tpds\\2.3.9\\lib\\site-packages\\tpds_extension\\cloud_connect\\TrustFlex\\assets\\AWS Connect.md'], app_id='fcbeb924595a9d88'), client_id='83d8713b71914961') C:\Users\C16779\tpds\2.3.9\lib\site-packages\tpds_extension\cloud_connect\TrustFlex\assets\AWS Connect.md
[DEBUG 2024-11-19 12:15:48,868 40348 33328] Websocket - Response: {"response": "file:///C:/Users/C16779/tpds/2.3.9/lib/site-packages/tpds_extension/cloud_connect/TrustFlex/assets/Help-AWS Connect.html", "status": "OK"}
[DEBUG 2024-11-19 12:15:48,868 40348 39048] handling link : file:///C:/Users/C16779/tpds/2.3.9/lib/site-packages/tpds_extension/cloud_connect/TrustFlex/assets/Help-AWS Connect.html
←[32mINFO←[0m:     connection closed
[DEBUG 2024-11-19 12:15:49,159 40348 39048] _handle_url_change: file:///C:/Users/C16779/tpds/2.3.9/lib/site-packages/tpds_extension/cloud_connect/TrustFlex/assets/Help-AWS Connect.html
[DEBUG 2024-11-19 12:15:49,275 40348 39048] onpagechange file:///C:/Users/C16779/tpds/2.3.9/lib/site-packages/tpds_extension/cloud_connect/TrustFlex/assets/Help-AWS Connect.html,
[DEBUG 2024-11-19 12:15:49,275 40348 39048] Help-AWS Connect.html
←[32mINFO←[0m:     127.0.0.1:54988 - "←[1mGET /boards/get_details/DM320118 HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     ('127.0.0.1', 55013) - "WebSocket /websocket" [accepted]
[DEBUG 2024-11-19 12:21:16,551 40348 33328] Websocket - Connecting Address(host='127.0.0.1', port=55013):Address(host='127.0.0.1', port=55013) as 4a587f7e11cab9e5
←[32mINFO←[0m:     connection open
[DEBUG 2024-11-19 12:21:16,553 40348 33328] Websocket - Recieved {"msg_id": 12, "parameters": ["CustomPKI Org", "<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>"], "app_id": "fcbeb924595a9d88"} from 4a587f7e11cab9e5
[DEBUG 2024-11-19 12:21:16,554 40348 33328] Processing Message: msg_id=<ReservedMessageId.user_input_text_box: 12> parameters=['CustomPKI Org', '<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>'] app_id='fcbeb924595a9d88'
[DEBUG 2024-11-19 12:21:16,555 40348 33328] _wrapper: MessageContext(parent=<tpds.app.app.TPDSApplication(0x25c868969e0) at 0x0000025C88736680>, message=OperationMessage(msg_id=<ReservedMessageId.user_input_text_box: 12>, parameters=['CustomPKI Org', '<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>'], app_id='fcbeb924595a9d88'), client_id='4a587f7e11cab9e5') CustomPKI Org <font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>
        <br>The organization name entered here would be used to
        generate TFLXTLS certificates.<br>
[DEBUG 2024-11-19 12:21:37,667 40348 33328] Websocket - Response: {"response": "ATStesting", "status": "OK"}
←[32mINFO←[0m:     connection closed
←[32mINFO←[0m:     127.0.0.1:56708 - "←[1mGET /boards/get_details/DM320118 HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     ('127.0.0.1', 56716) - "WebSocket /websocket" [accepted]
[DEBUG 2024-11-19 12:59:40,361 40348 33328] Websocket - Connecting Address(host='127.0.0.1', port=56716):Address(host='127.0.0.1', port=56716) as 3718b517aef96bd9
←[32mINFO←[0m:     connection open
[DEBUG 2024-11-19 12:59:40,363 40348 33328] Websocket - Recieved {"msg_id": 12, "parameters": ["CustomPKI Org", "<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>"], "app_id": "fcbeb924595a9d88"} from 3718b517aef96bd9
[DEBUG 2024-11-19 12:59:40,363 40348 33328] Processing Message: msg_id=<ReservedMessageId.user_input_text_box: 12> parameters=['CustomPKI Org', '<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>'] app_id='fcbeb924595a9d88'
[DEBUG 2024-11-19 12:59:40,364 40348 33328] _wrapper: MessageContext(parent=<tpds.app.app.TPDSApplication(0x25c868969e0) at 0x0000025C88736680>, message=OperationMessage(msg_id=<ReservedMessageId.user_input_text_box: 12>, parameters=['CustomPKI Org', '<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>'], app_id='fcbeb924595a9d88'), client_id='3718b517aef96bd9') CustomPKI Org <font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>
        <br>The organization name entered here would be used to
        generate TFLXTLS certificates.<br>
[DEBUG 2024-11-19 12:59:44,703 40348 33328] Websocket - Response: {"response": "testest", "status": "OK"}
←[32mINFO←[0m:     connection closed
←[32mINFO←[0m:     127.0.0.1:56727 - "←[1mGET /boards/get_details/DM320118 HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     ('127.0.0.1', 56730) - "WebSocket /websocket" [accepted]
[DEBUG 2024-11-19 12:59:47,034 40348 33328] Websocket - Connecting Address(host='127.0.0.1', port=56730):Address(host='127.0.0.1', port=56730) as 19dd40dfb1cc57a6
←[32mINFO←[0m:     connection open
[DEBUG 2024-11-19 12:59:47,043 40348 33328] Websocket - Recieved {"msg_id": 12, "parameters": ["CustomPKI Org", "<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>"], "app_id": "fcbeb924595a9d88"} from 19dd40dfb1cc57a6
[DEBUG 2024-11-19 12:59:47,043 40348 33328] Processing Message: msg_id=<ReservedMessageId.user_input_text_box: 12> parameters=['CustomPKI Org', '<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>'] app_id='fcbeb924595a9d88'
[DEBUG 2024-11-19 12:59:47,044 40348 33328] _wrapper: MessageContext(parent=<tpds.app.app.TPDSApplication(0x25c868969e0) at 0x0000025C88736680>, message=OperationMessage(msg_id=<ReservedMessageId.user_input_text_box: 12>, parameters=['CustomPKI Org', '<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>'], app_id='fcbeb924595a9d88'), client_id='19dd40dfb1cc57a6') CustomPKI Org <font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>
        <br>The organization name entered here would be used to
        generate TFLXTLS certificates.<br>
[DEBUG 2024-11-19 12:59:52,592 40348 33328] Websocket - Response: {"response": "dqsasdasdf", "status": "OK"}
←[32mINFO←[0m:     connection closed
←[32mINFO←[0m:     connection closed
[DEBUG 2024-11-19 13:00:49,816 40348 13608] [I 13:00:49.813 NotebookApp] Starting buffering for b548a499-2177-4aee-9762-c18892a23340:a1edb0e0-e9df-46f2-8f9c-e14f95126f61
←[32mINFO←[0m:     connection closed
qt.qpa.screen: "Unable to open monitor interface to \\\\.\\DISPLAY1:" "The operation completed successfully."
qt.qpa.screen: "Unable to open monitor interface to \\\\.\\DISPLAY1:" "The operation completed successfully."
[DEBUG 2024-11-19 13:01:15,224 40348 39048] JS:http://localhost:8888/voila/render/cloud_connect/TrustFlex/AWS%20Connect-Custom%20PKI-TFLEX.ipynb?id=fcbeb924595a9d88 Line#40: b'Connection lost, reconnecting in 0 seconds.'
[DEBUG 2024-11-19 13:01:15,484 40348 39048] JS:http://localhost:8888/voila/render/cloud_connect/TrustFlex/AWS%20Connect-Custom%20PKI-TFLEX.ipynb?id=fcbeb924595a9d88 Line#30: b'Starting WebSocket: ws://localhost:8888/api/kernels/b548a499-2177-4aee-9762-c18892a23340'
[DEBUG 2024-11-19 13:01:18,176 40348 13608] [I 13:01:18.175 NotebookApp] Restoring connection for b548a499-2177-4aee-9762-c18892a23340:a1edb0e0-e9df-46f2-8f9c-e14f95126f61
←[32mINFO←[0m:     127.0.0.1:63987 - "←[1mGET /boards/get_details/DM320118 HTTP/1.1←[0m" ←[32m200 OK←[0m
←[32mINFO←[0m:     ('127.0.0.1', 63988) - "WebSocket /websocket" [accepted]
[DEBUG 2024-11-19 13:03:00,343 40348 33328] Websocket - Connecting Address(host='127.0.0.1', port=63988):Address(host='127.0.0.1', port=63988) as f9a0a6145654d16c
←[32mINFO←[0m:     connection open
[DEBUG 2024-11-19 13:03:00,345 40348 33328] Websocket - Recieved {"msg_id": 12, "parameters": ["CustomPKI Org", "<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>"], "app_id": "fcbeb924595a9d88"} from f9a0a6145654d16c
[DEBUG 2024-11-19 13:03:00,346 40348 33328] Processing Message: msg_id=<ReservedMessageId.user_input_text_box: 12> parameters=['CustomPKI Org', '<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>'] app_id='fcbeb924595a9d88'
[DEBUG 2024-11-19 13:03:00,346 40348 33328] _wrapper: MessageContext(parent=<tpds.app.app.TPDSApplication(0x25c868969e0) at 0x0000025C88736680>, message=OperationMessage(msg_id=<ReservedMessageId.user_input_text_box: 12>, parameters=['CustomPKI Org', '<font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>\n        <br>The organization name entered here would be used to\n        generate TFLXTLS certificates.<br>'], app_id='fcbeb924595a9d88'), client_id='f9a0a6145654d16c') CustomPKI Org <font color=#0000ff><b>Enter Org Name for Custom PKI</b></font><br>
        <br>The organization name entered here would be used to
        generate TFLXTLS certificates.<br>
[DEBUG 2024-11-19 13:03:03,102 40348 33328] Websocket - Response: {"response": "dewfeerqf", "status": "OK"}
←[32mINFO←[0m:     connection closed
[DEBUG 2024-11-19 13:05:57,064 40348 39048] _handle_url_change: https://github.com/Microchip-TrustPlatformDesignSuite/TPDS-Issue-Tracker/issues/new?body=Issue+Type%3A+%3Cb%3EBug+Report%3C%2Fb%3E%0A%23%23%23%23+tpds-application%3A+2.3.17%0A%23%23%23%23+tpds-application-root%3A+2.3.12%0A%23%23%23%23+tpds-boards%3A+2.2.11%0A%23%23%23%23+tpds-cec-utilities%3A+1.3.0%0A%23%23%23%23+tpds-certificate-tools%3A+1.0.2%0A%23%23%23%23+tpds-core%3A+2.3.19%0A%23%23%23%23+tpds-extension-aes-message-encryption%3A+1.0.1%0A%23%23%23%23+tpds-extension-avnet-iotconnect%3A+2.2.4%0A%23%23%23%23+tpds-extension-cec17xx-support%3A+1.3.3%0A%23%23%23%23+tpds-extension-cryptoquantique-quarklink%3A+1.0.3%0A%23%23%23%23+tpds-extension-dspic33-support%3A+1.0.1%0A%23%23%23%23+tpds-extension-ecc204-support%3A+1.9.2%0A%23%23%23%23+tpds-extension-ecc608-sip-support%3A+1.6.4%0A%23%23%23%23+tpds-extension-keystream-connect%3A+1.1.1%0A%23%23%23%23+tpds-extension-secureboot%3A+1.3.0%0A%23%23%23%23+tpds-extension-sha104-105-support%3A+1.2.2%0A%23%23%23%23+tpds-extension-spg-asym-auth%3A+2.0.4%0A%23%23%23%23+tpds-extension-spg-cloud-connect%3A+2.3.5%0A%23%23%23%23+tpds-extension-spg-fw-validation%3A+2.2.4%0A%23%23%23%23+tpds-extension-spg-ip-protection%3A+2.2.3%0A%23%23%23%23+tpds-extension-spg-public-key-rotation%3A+2.2.4%0A%23%23%23%23+tpds-extension-spg-symmetric-auth%3A+2.2.4%0A%23%23%23%23+tpds-extension-ta010-support%3A+1.6.1%0A%23%23%23%23+tpds-extension-wpc-transmitter%3A+2.3.6%0A%23%23%23%23+tpds-helper%3A+2.3.18%0A%23%23%23%23+tpds-manifest%3A+1.0.8%0A%23%23%23%23+tpds-schema%3A+1.2.1%0A%23%23%23%23+tpds-voila-template%3A+2.2.3%0A%0A%0A%3C%21--+Add+Issue+description+below+--%3E%0A
QLayout::removeWidget: Cannot remove a null widget.

**Comment by ABHIJITH-KOTA-MICROCHIP** [comment]
Hi @bugabuga64 ,

Can you please cross-check the AWS region in the ~/.trustplatform/aws_credentials.yaml file and try again?
